```{r}
setwd("C:/Users/xbw/Desktop/SourceClass/SIMLR")
# required external packages for SIMLR
library(Matrix)
library(parallel)

# load the igraph package to compute the NMI
library(igraph)

# load the palettes for the plots
library(grDevices)

# load the SIMLR R package
source("./R/SIMLR.R")
source("./R/compute.multiple.kernel.R")
source("./R/network.diffusion.R")
source("./R/utils.simlr.R")
source("./R/tsne.R")

dyn.load("./R/projsplx_R.dll")

```


```{r}
Fm <- read.csv("../matrix_data/F.csv", header = FALSE , sep = ",", quote = "", fill = TRUE)
Q <- read.csv("../matrix_data/Q.csv", header = FALSE , sep = ",", quote = "", fill = TRUE)
L <- read.csv("../matrix_data/L.csv", header = FALSE , sep = ",", quote = "", fill = TRUE)
Fm <- as.matrix(Fm)
Q <- as.matrix(Q)
L <- as.matrix(L) + 1
cn = 2

set.seed(33333)
simlr_m = SIMLR(X=t(Fm) ,c=cn)
```

```{r}
nmi_3 = compare(L,simlr_m$y$cluster,method="nmi")
# make the scatterd plots
plot(simlr_m$ydata,col=c(topo.colors(cn))[L],xlab="SIMLR component 1", ylab="SIMLR component 2",pch=20,main="SIMILR 2D visualization for Test_1_mECS")

```
```{r}
# coldiss()
# Color plots of a dissimilarity matrix, without and with ordering
#
# License: GPL-2 
# Author: Francois Gillet, August 2009
#
library(cluster)
library(gclus)

"coldiss" <- function(D, nc = 4, byrank = TRUE, diag = FALSE)
{
	require(gclus)

	if (max(D)>1) D <- D/max(D)

	if (byrank) {
		spe.color = dmat.color(1-D, cm.colors(nc))
	}
	else {
		spe.color = dmat.color(1-D, byrank=FALSE, cm.colors(nc))
	}

	spe.o = order.single(1-D)
	speo.color = spe.color[spe.o,spe.o]
	
	op = par(mfrow=c(1,2), pty="s")

	if (diag) {
		plotcolors(spe.color, rlabels=attributes(D)$Labels, 
			main="Dissimilarity Matrix", 
			dlabels=attributes(D)$Labels)
		plotcolors(speo.color, rlabels=attributes(D)$Labels[spe.o], 
			main="Ordered Dissimilarity Matrix", 
			dlabels=attributes(D)$Labels[spe.o])
	}
	else {
		plotcolors(spe.color, rlabels=attributes(D)$Labels, 
			main="Dissimilarity Matrix")
		plotcolors(speo.color, rlabels=attributes(D)$Labels[spe.o], 
			main="Ordered Dissimilarity Matrix")
	}

	par(op)
}


```


```{r}
D_map = dist2(simlr_m$ydata)
dim(D_map)
coldiss(D_map, nc = 2, byrank = TRUE, diag = FALSE)
```

